---
- name: Ensure our secret file is in place for non-containerized aap
  become: true
  become_user: root
  tags:
    - legacy
  ansible.builtin.copy:
    src: files/{{ aap_cert_renewal_secret_file_name }}
    dest: /root/.ssh/secret
    owner: root
    group: root
    mode: '0600'
    decrypt: true

- name: Ensure our secret file is in place for containerized aap
  tags:
    - container
  ansible.builtin.copy:
    src: files/{{ aap_cert_renewal_secret_file_name }}
    dest: /home/ansible-svc/.ssh/secret
    owner: ansible-svc
    group: ansible-svc
    mode: '0600'
    decrypt: true

- name: Ensure we have the AAP bundle directory
  tags:
    - container
  register: aap_bundle_dir
  changed_when: false
  ansible.builtin.shell: ls -d /home/ansible-svc/ansible-automation-platform-containerized-*

- name: Ensure we have the non-containerized AAP bundle directory
  tags:
    - legacy
  become: true
  become_user: root
  register: non_containerized_aap_bundle_dir
  changed_when: false
  ansible.builtin.shell: ls -d /root/ansible-automation-platform-setup-bundle-*

- name: Ensure the containerized inventory file is configured to renew the ssl cert
  tags:
    - container
  ansible.builtin.template:
    src: templates/containerized_aap_24_inventory_controller_file_cert_renewal.j2
    dest: "{{ aap_bundle_dir.stdout }}/inventory"
    owner: ansible-svc
    group: ansible-svc
    mode: "0644"
    backup: true

- name: Ensure the legacy inventory file is configured to renew the ssl cert
  tags:
    - legacy
  become: true
  become_user: root
  ansible.builtin.template:
    src: templates/legacy_aap_24_inventory_controller_file.j2
    dest: "{{ non_containerized_aap_bundle_dir.stdout }}/inventory"
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Copy vault into place
  tags:
    - container
  ansible.builtin.copy:
    src: files/{{ vault_file_name }}
    dest: "{{ aap_bundle_dir.stdout }}/{{ aap_cert_renewal_vault_file_name }}"
    owner: ansible-svc
    group: ansible-svc
    mode: '0644'
    decrypt: false

- name: Copy vault into place
  tags:
    - legacy
  become: true
  become_user: root
  ansible.builtin.copy:
    src: files/{{ vault_file_name }}
    dest: "{{ non_containerized_aap_bundle_dir.stdout }}/{{ aap_cert_renewal_vault_file_name }}"
    owner: root
    group: root
    mode: '0644'
    decrypt: false
